name: CI Angular app
on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install packages
        run: npm i
      - name: Setup CI environment
        run: npm ci
      - name: Run tests
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install packages
        run: npm i
      - name: Setup CI environment
        run: npm ci
      - name: Lint code
        run: npm run lint